export { default as WelcomeNavbar } from './WelcomeNavbar'
export { default as WelcomeFooter } from './WelcomeFooter'
export { default as Features } from './Features'
export { default as Destinations } from './Destinations'
export { default as About } from './About'
export { default as Contact } from './Contact'
